name: components_qt_kit
description: helper widget packages for qt projects.
version: 0.1.3
homepage: https://github.com/tobiassilva/components_qt_kit.git
 
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity: ^3.0.6
  crypto: ^3.0.1
  firebase_analytics: ^9.1.4
  firebase_auth: ^3.1.0
  firebase_auth_web: ^3.1.0
  firebase_core: ^1.6.0
  firebase_database: ^9.0.10
  firebase_messaging: ^11.2.12
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.0.1
  font_awesome_flutter: ^10.1.0
  google_sign_in: ^5.3.0
  http: ^0.13.4
  multi_image_picker2: ^5.0.02
  provider: ^6.0.3
  sign_in_with_apple: ^3.0.0
  flutter_mobx: ^2.0.2
  mobx: ^2.0.4
  mobx_codegen: ^2.0.3
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
